name: mcorec_sep
channels:
  - defaults
  - https://software.repos.intel.com/python/conda/
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - cairo=1.16.0
  - dav1d=1.2.1
  - expat=2.7.1
  - ffmpeg=6.1.1
  - fontconfig=2.14.1
  - freetype=2.13.3
  - giflib=5.2.2
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - jpeg=9e
  - lame=3.100
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.7.7
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - ncurses=6.5
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - pcre2=10.42
  - pip=25.1
  - pixman=0.46.4
  - pthread-stubs=0.3
  - python=3.11.13
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tesseract=5.2.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.7.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.3.0
      - av==12.0.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.2.1
      - datasets==3.6.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - ffmpeg-python==0.2.0
      - filelock==3.19.1
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-transfer==0.1.9
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - idna==3.10
      - imageio==2.37.0
      - jinja2==3.1.6
      - jiwer==3.0.5
      - joblib==1.5.1
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.5
      - numpy==2.3.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.10.0.84
      - packaging==25.0
      - pandas==2.3.2
      - pillow==11.3.0
      - platformdirs==4.3.8
      - propcache==0.3.2
      - protobuf==5.29.5
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pycparser==3.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - python-dateutil==2.9.0.post0
      - python-speech-features==0.6
      - pytz==2025.2
      - pyyaml==6.0.2
      - rapidfuzz==3.13.0
      - regex==2025.7.34
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.16.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.35.0
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - soundfile==0.12.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.6.11
      - tokenizers==0.21.4
      - torch==2.7.1
      - torch-summary==1.4.5
      - torchaudio==2.7.1
      - torchcodec==0.4.0
      - torchmetrics==1.2.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.52.4
      - triton==3.3.1
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.19.1
      - webvtt-py==0.5.1
      - xxhash==3.5.0
      - yarl==1.20.1
